-- Add required columns to existing subscribers table and create optional send_logs table.
-- Safe: additive only, uses IF NOT EXISTS, no updates to existing columns.

-- 1) Extend subscribers (imported from GetResponse).
ALTER TABLE IF EXISTS public.subscribers
  ADD COLUMN IF NOT EXISTS project_id uuid,
  ADD COLUMN IF NOT EXISTS version integer DEFAULT 1,
  ADD COLUMN IF NOT EXISTS is_current boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS bounce_type text,
  ADD COLUMN IF NOT EXISTS bounce_subtype text,
  ADD COLUMN IF NOT EXISTS status_updated_at timestamptz,
  ADD COLUMN IF NOT EXISTS from_name text;

-- Optional indexes to support common access patterns.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'subscribers'
      AND column_name = 'email'
  ) THEN
    CREATE INDEX IF NOT EXISTS subscribers_project_status_idx
      ON public.subscribers (project_id, status);
    CREATE INDEX IF NOT EXISTS subscribers_project_email_idx
      ON public.subscribers (project_id, email);
  END IF;
END $$;

-- 2) Optional send_logs table for local tracking.
CREATE TABLE IF NOT EXISTS public.send_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id uuid NOT NULL,
  version integer NOT NULL DEFAULT 1,
  is_current boolean NOT NULL DEFAULT true,
  mailout_id text,
  email text,
  status text,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT send_logs_status_check
    CHECK (status IS NULL OR status IN ('sent', 'failed'))
);

CREATE INDEX IF NOT EXISTS send_logs_project_mailout_idx
  ON public.send_logs (project_id, mailout_id);

CREATE INDEX IF NOT EXISTS send_logs_project_email_idx
  ON public.send_logs (project_id, email);
